# Generated by Django 3.2.8 on 2021-10-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(max_length=100)),
                ('UIC', models.IntegerField()),
                ('eventStartDateTime', models.DateTimeField()),
                ('eventEndDateTime', models.DateTimeField()),
                ('totalTestCases', models.IntegerField()),
                ('totalTestCasesPassed', models.IntegerField()),
                ('totalTestCasesFailed', models.IntegerField()),
                ('testUptime', models.FloatField()),
                ('eventStatus', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked')], max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
