# Generated by Django 3.2.8 on 2021-10-25 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prototype',
            name='totalElapsedTime',
            field=models.TimeField(default=datetime.time(12, 31, 45, 561618)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prototype',
            name='testUptime',
            field=models.TimeField(),
        ),
    ]
