#!/usr/bin/bash

 

if [ $UID != 0 ]; then
  echo "You must be root to run this application."
  exit 1
fi
scp bin/Gemini .
export LD_LIBRARY_PATH=$(pwd)/Libraries
echo "Running from $(pwd)"
./Gemini config/config.gii
rm Gemini
