# Generated by Django 3.2.8 on 2021-12-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CUI', 'Cui'), ('FOUO', 'Fouo'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
