# Generated by Django 3.2.8 on 2021-12-20 14:48

from django.db import migrations

from django.contrib.auth.management import create_permissions

def create_groups(apps, schema_migration):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "permission")
    print("\n")
    print(Permission.objects.all())
    print("\n")

    add_classifiedupload = Permission.objects.get(codename="add_classifiedupload")
    change_classifiedupload = Permission.objects.get(codename="change_classifiedupload")
    delete_classifiedupload = Permission.objects.get(codename="delete_classifiedupload")
    view_classifiedupload = Permission.objects.get(codename="view_classifiedupload")

    write_perms = [
        add_classifiedupload,
        change_classifiedupload,
        delete_classifiedupload,
        view_classifiedupload
    ]

    writeGroup = Group(name="Write Permissions")
    writeGroup.save()
    writeGroup.permissions.set(write_perms)

    readGroup = Group(name="Read-Only Permissions")
    readGroup.save()
    readGroup.permissions.add(view_classifiedupload)
    
class Migration(migrations.Migration):

    dependencies = [
        ('headerUploadTest', '0001_initial'),
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
