#ifndef FACTORYINTERFACE_H
#define FACTORYINTERFACE_H

#include <memory>
#include <vector>
#include <string>

#include "abstractdriver.h"

// interface requests the code autogenerated -- requests the code autogenerated meaning
// requesting the plugin of the factory implementation of that message?


class FactoryInterface
{

    public:
        // virtual function that makes this class abstract, i.e. an interface
        virtual int GetTopicCount() = 0;
        virtual std::vector<std::string> GetTopicList() = 0;
        virtual std::vector<std::unique_ptr<AbstractDriver>> GetTopicFactories() = 0;
        virtual std::string toString() = 0;

};
#endif
