name: "Simple Math test"
description: "Do simple math tests with parameters from main.yml"
author: "Brian Dillon"

inputs:
  OPERAND1:
    description: "Passed in"
    required: false
  OPERAND2:
    description: "Passed in"
    required: false
  ANSWER:
    description: "Passed in"
    required: false
  PASSES:
    description: "Whether the test should pass or not"
    required: true

jobs:
  test:
    runs:
      using: "docker"
      image: "Dockerfile"
      steps:
      - name: Save File listing
        run: ls html/ > out.txt
      - name: Keep file listing artifact
        uses: actions/upload-artifact@v1
        with:
          name: file_list
          path: out.txt
