name: "Simple Math test"
description: "Do simple math tests with parameters from main.yml"
author: "Brian Dillon"

inputs:
  OPERAND1:
    description: "Passed in"
    required: false
  OPERAND2:
    description: "Passed in"
    required: false
  ANSWER:
    description: "Passed in"
    required: false
  PASSES:
    description: "Whether the test should pass or not"
    required: true

jobs:
  build:
    runs:
      using: "docker"
      image: "Dockerfile"
    steps:
    - uses: actions/checkout@v1
    - name: Test case
      uses: ./.github/actions/mathTest
      with:
        OPERAND1: INPUT_OPERAND1
        OPERAND2: INPUT_OPERAND2
        ANSWER: INPUT_ANSWER
    - name: Check pass
      if: ${{ success() }}
      run: exit 1-INPUT_PASSES
    - name: Check fail
      if: ${{ failure() }}
      run: exit 0+INPUT_PASSES