# Generated by Django 3.2.8 on 2021-12-20 14:48

# This file is a template for generating groups and permissions automatically when first creating the server.
# This step takes place after running "python manage.py makemigrations" for the first time, but before using "python manage.py migrate"
# After the initial makemigrations, run "python manage.py makemigrations --empty headerUploadTest", replacing your app name as necessary.
# Enter the "migrations" directory in your main app folder (this file is in headerUploadTest's) and copy this code into the generated .py file there, which should have a name that includes "auto" and "0002"
# Modify this code according to the desired effect, and then finally run "python manage.py migrate"

from django.db import migrations

from django.contrib.auth.management import create_permissions

def create_groups(apps, schema_migration):
    # This section generates the permissions you will need early.
    # Normally the permissions are generated after all migrations have been completed.
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    # Get the Group and Permission models
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "permission")
    
    # Since you need the permission code names and you don't readily get to define those, you may want to loop through Permission.objects.all() to figure out the right ones.
    # You can "reset" the server by deleting the database and erasing all non-init files from the migrations directory - you must makemigrations again from the start.

    add_classifiedupload = Permission.objects.get(codename="add_classifiedupload")
    change_classifiedupload = Permission.objects.get(codename="change_classifiedupload")
    delete_classifiedupload = Permission.objects.get(codename="delete_classifiedupload")
    view_classifiedupload = Permission.objects.get(codename="view_classifiedupload")

    write_perms = [
        add_classifiedupload,
        change_classifiedupload,
        delete_classifiedupload,
        view_classifiedupload
    ]

    writeGroup = Group(name="Write Permissions")
    writeGroup.save()
    writeGroup.permissions.set(write_perms)

    readGroup = Group(name="Read-Only Permissions")
    readGroup.save()
    readGroup.permissions.add(view_classifiedupload)
    
class Migration(migrations.Migration):

    # The headerUploadTest dependency is added automatically. The other dependencies are just in case.
    dependencies = [
        ('headerUploadTest', '0001_initial'),
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
    ]

    # Note that the function called within RunPython must already be defined - order matters, so that function must be defined before/above the Migration class.
    operations = [
        migrations.RunPython(create_groups)
    ]
