var testRuns = {
 "20210630 16:06:50.482" : [
{ Parameters: '${SITE URL}${BROWSER}, JavaScript Test Tool, , ', Test: 'Open Site', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio1, ', Test: 'Radio Test 1', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio2, ', Test: 'Radio Test 2', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio3, ', Test: 'Radio Test 3', Status: 'PASS', Message: ""}, 
 { Parameters: ', Radio4, ', Test: 'Radio Test 4', Status: 'FAIL', Message: "Button with locator 'Radio4' not found."}, 
 { Parameters: 'fileName, fileNametextfile1.txt, openfile, fileOutputValue1, , ', Test: 'Textbox Test', Status: 'PASS', Message: ""}, 
 { Parameters: 'date, date12/12/2020, , date12/12/2020, , , ', Test: 'Date Test', Status: 'FAIL', Message: "Element 'date' should have contained text '12/12/2020' but its text was ''."}, 
 ], 
 "20210630 16:07:47.511" : [
{ Parameters: '${SITE URL}${BROWSER}, JavaScript Test Tool, , ', Test: 'Open Site', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio1, ', Test: 'Radio Test 1', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio2, ', Test: 'Radio Test 2', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio3, ', Test: 'Radio Test 3', Status: 'PASS', Message: ""}, 
 { Parameters: ', Radio4, ', Test: 'Radio Test 4', Status: 'FAIL', Message: "Button with locator 'Radio4' not found."}, 
 { Parameters: 'fileName, fileNametextfile1.txt, openfile, fileOutputValue1, , ', Test: 'Textbox Test', Status: 'PASS', Message: ""}, 
 { Parameters: 'date, date12/12/2020, , date12/12/2020, , , ', Test: 'Date Test', Status: 'FAIL', Message: "Element 'date' should have contained text '12/12/2020' but its text was ''."}, 
 ], 
 "20210630 16:08:00.514" : [
{ Parameters: '${SITE URL}${BROWSER}, JavaScript Test Tool, , ', Test: 'Open Site', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio1, ', Test: 'Radio Test 1', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio2, ', Test: 'Radio Test 2', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio3, ', Test: 'Radio Test 3', Status: 'PASS', Message: ""}, 
 { Parameters: ', Radio4, ', Test: 'Radio Test 4', Status: 'FAIL', Message: "Button with locator 'Radio4' not found."}, 
 { Parameters: 'fileName, fileNametextfile1.txt, openfile, fileOutputValue1, , ', Test: 'Textbox Test', Status: 'PASS', Message: ""}, 
 { Parameters: 'date, date12/12/2020, , date12/12/2020, , , ', Test: 'Date Test', Status: 'FAIL', Message: "Element 'date' should have contained text '12/12/2020' but its text was ''."}, 
 ], 
 "20210630 16:09:08.501" : [
{ Parameters: '${SITE URL}${BROWSER}, JavaScript Test Tool, , ', Test: 'Open Site', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio1, ', Test: 'Radio Test 1', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio2, ', Test: 'Radio Test 2', Status: 'PASS', Message: ""}, 
 { Parameters: 'Radio3, ', Test: 'Radio Test 3', Status: 'PASS', Message: ""}, 
 { Parameters: ', Radio4, ', Test: 'Radio Test 4', Status: 'FAIL', Message: "Button with locator 'Radio4' not found."}, 
 { Parameters: 'fileName, fileNametextfile1.txt, openfile, fileOutputValue1, , ', Test: 'Textbox Test', Status: 'PASS', Message: ""}, 
 { Parameters: 'date, date12/12/2020, , date12/12/2020, , , ', Test: 'Date Test', Status: 'FAIL', Message: "Element 'date' should have contained text '12/12/2020' but its text was ''."}, 
 ], 
 };